### ISSUE TITLE
Will scriptors get detected and get no allocation?

### ISSUE THREAD

**Issue by surendra841** [Solana0x/GrassNode2#2]
Just wanted to know, if anyone got qualified without getting the points slashed for the Season 1 Airdrop using script? 

If got Qualified, how much was your allocation?

**Comment by Solana0x** [comment]
I got a Good allocation Last time :) also i dont think any user of My old Stage 1 script was marked for sybil because We are not sybil ! We are having 1 account and many devices ! thats it !! and that is allowed :)

we are 1st one 

![image](https://github.com/user-attachments/assets/bf2e35ef-0815-4f8a-8cb2-844dd1371a2b)

**Comment by surendra841** [comment]
Are Residential Proxies, good?
